In [10]:
import imp, os
import pandas as pd
import numpy as np
#load the modules from the right dir...
imp.load_source('app', 'app.py')
from app import *

In [11]:
db_conn = DbCon()
df = db_conn.get_accounts()
df

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Username</th>
      <th>pDonaterRank</th>
      <th>Score</th>
      <th>Kills</th>
      <th>Deaths</th>
    </tr>
    <tr>
      <th>Account_ID</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>Kar</td>
      <td>3</td>
      <td>1085</td>
      <td>716</td>
      <td>140</td>
    </tr>
    <tr>
      <th>2</th>
      <td>KCNR</td>
      <td>0</td>
      <td>4</td>
      <td>1</td>
      <td>6</td>
    </tr>
    <tr>
      <th>4</th>
      <td>ONX</td>
      <td>0</td>
      <td>-244</td>
      <td>116</td>
      <td>445</td>
    </tr>
    <tr>
      <th>8</th>
      <td>RasmusR</td>
      <td>0</td>
      <td>154</td>
      <td>8</td>
      <td>37</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Strike</td>
      <td>0</td>
      <td>4388</td>
      <td>1472</td>
      <td>657</td>
    </tr>
    <tr>
      <th>16</th>
      <td>vitaliy</td>
      <td>3</td>
      <td>30109</td>
      <td>3607</td>
      <td>3247</td>
    </tr>
    <tr>
      <th>21</th>
      <td>JuiceBox</td>
      <td>3</td>
      <td>5639</td>
      <td>1372</td>
      <td>1685</td>
    </tr>
    <tr>
      <th>24</th>
      <td>WAYNE</td>
      <td>3</td>
      <td>12795</td>
      <td>1323</td>
      <td>2296</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Yezpahr</td>
      <td>3</td>
      <td>24143</td>
      <td>3021</td>
      <td>2792</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Peter</td>
      <td>3</td>
      <td>220</td>
      <td>1144</td>
      <td>686</td>
    </tr>
    <tr>
      <th>45</th>
      <td>AntreCot</td>
      <td>0</td>
      <td>961</td>
      <td>0</td>
      <td>79</td>
    </tr>
    <tr>
      <th>49</th>
      <td>$$$Ivan@@</td>
      <td>0</td>
      <td>10225</td>
      <td>607</td>
      <td>1003</td>
    </tr>
    <tr>
      <th>53</th>
      <td>Amombob</td>
      <td>0</td>
      <td>2993</td>
      <td>356</td>
      <td>840</td>
    </tr>
    <tr>
      <th>58</th>
      <td>.CaRisMa.</td>
      <td>0</td>
      <td>7617</td>
      <td>1556</td>
      <td>1464</td>
    </tr>
    <tr>
      <th>73</th>
      <td>aimandkill</td>
      <td>3</td>
      <td>10847</td>
      <td>2241</td>
      <td>2463</td>
    </tr>
    <tr>
      <th>75</th>
      <td>Bruce_Bond</td>
      <td>3</td>
      <td>19713</td>
      <td>3464</td>
      <td>2716</td>
    </tr>
    <tr>
      <th>81</th>
      <td>syaldi</td>
      <td>0</td>
      <td>33</td>
      <td>2</td>
      <td>70</td>
    </tr>
    <tr>
      <th>91</th>
      <td>MASSAS</td>
      <td>0</td>
      <td>4489</td>
      <td>108</td>
      <td>375</td>
    </tr>
    <tr>
      <th>92</th>
      <td>coZZixx</td>
      <td>0</td>
      <td>671</td>
      <td>40</td>
      <td>135</td>
    </tr>
    <tr>
      <th>103</th>
      <td>Finduslax</td>
      <td>0</td>
      <td>2963</td>
      <td>636</td>
      <td>1097</td>
    </tr>
    <tr>
      <th>123</th>
      <td>Ingstaad</td>
      <td>0</td>
      <td>-6</td>
      <td>0</td>
      <td>9</td>
    </tr>
    <tr>
      <th>124</th>
      <td>SmokeEST</td>
      <td>0</td>
      <td>2187</td>
      <td>24</td>
      <td>34</td>
    </tr>
    <tr>
      <th>125</th>
      <td>Sikais</td>
      <td>0</td>
      <td>37</td>
      <td>37</td>
      <td>71</td>
    </tr>
    <tr>
      <th>128</th>
      <td>Archesten</td>
      <td>1</td>
      <td>7055</td>
      <td>1178</td>
      <td>604</td>
    </tr>
    <tr>
      <th>135</th>
      <td>Wet_Your_Pants</td>
      <td>2</td>
      <td>12279</td>
      <td>1712</td>
      <td>1708</td>
    </tr>
    <tr>
      <th>136</th>
      <td>ArletKuppart</td>
      <td>0</td>
      <td>3358</td>
      <td>5</td>
      <td>8</td>
    </tr>
    <tr>
      <th>138</th>
      <td>Prevous32</td>
      <td>0</td>
      <td>18</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>146</th>
      <td>Fuet</td>
      <td>2</td>
      <td>15383</td>
      <td>1540</td>
      <td>2573</td>
    </tr>
    <tr>
      <th>155</th>
      <td>Sneekerpikie</td>
      <td>1</td>
      <td>1689</td>
      <td>94</td>
      <td>330</td>
    </tr>
    <tr>
      <th>158</th>
      <td>Forcezx</td>
      <td>2</td>
      <td>6685</td>
      <td>1190</td>
      <td>1572</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>353636</th>
      <td>Taanta</td>
      <td>0</td>
      <td>5</td>
      <td>3</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353637</th>
      <td>gi_joe</td>
      <td>0</td>
      <td>4</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353638</th>
      <td>Aywa_eL4ay</td>
      <td>0</td>
      <td>4</td>
      <td>4</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353639</th>
      <td>_hNxX</td>
      <td>0</td>
      <td>5</td>
      <td>7</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353640</th>
      <td>GenjiSuzuran</td>
      <td>0</td>
      <td>7</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>353641</th>
      <td>3aMKoO_</td>
      <td>0</td>
      <td>5</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353642</th>
      <td>edilo_</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353643</th>
      <td>mhab20176</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>6</td>
    </tr>
    <tr>
      <th>353644</th>
      <td>xXTbawyXx</td>
      <td>0</td>
      <td>5</td>
      <td>10</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353645</th>
      <td>Layla</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353646</th>
      <td>Hero2017</td>
      <td>0</td>
      <td>4</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353647</th>
      <td>PantatDimitri</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353648</th>
      <td>PantatSpector</td>
      <td>0</td>
      <td>25</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353649</th>
      <td>CykaBlyat</td>
      <td>0</td>
      <td>11</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353650</th>
      <td>KentutBusuk</td>
      <td>0</td>
      <td>39</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353651</th>
      <td>mr______yosaf</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353652</th>
      <td>MR...ALI</td>
      <td>0</td>
      <td>3</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353653</th>
      <td>Shrood</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353654</th>
      <td>kkssaa</td>
      <td>0</td>
      <td>4</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353655</th>
      <td>Robke_Veyrone</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353656</th>
      <td>Mafija_Bass</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353657</th>
      <td>mmmaaasssddd</td>
      <td>0</td>
      <td>6</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353658</th>
      <td>kkssaahh</td>
      <td>0</td>
      <td>6</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353659</th>
      <td>mr____pop1</td>
      <td>0</td>
      <td>2</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>353660</th>
      <td>SneakyGhost</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>5</td>
    </tr>
    <tr>
      <th>353661</th>
      <td>Loh_Jibanij</td>
      <td>0</td>
      <td>4</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>353662</th>
      <td>Stepka_Bass</td>
      <td>0</td>
      <td>4</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>353663</th>
      <td>Zeimeris_Bulviakasis</td>
      <td>0</td>
      <td>3</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>353664</th>
      <td>The_Armenyan_King</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>353665</th>
      <td>Pavle_Rudinac</td>
      <td>0</td>
      <td>5</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>227977 rows × 5 columns</p>
</div>

In [15]:
df = df[df['Kills'] > 10]
df = df[df['Deaths'] > 10]
df['kd_ratio'] = df['Kills']/df['Deaths']
df

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Username</th>
      <th>pDonaterRank</th>
      <th>Score</th>
      <th>Kills</th>
      <th>Deaths</th>
      <th>kd_ratio</th>
    </tr>
    <tr>
      <th>Account_ID</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>Kar</td>
      <td>3</td>
      <td>1085</td>
      <td>716</td>
      <td>140</td>
      <td>5.114286</td>
    </tr>
    <tr>
      <th>4</th>
      <td>ONX</td>
      <td>0</td>
      <td>-244</td>
      <td>116</td>
      <td>445</td>
      <td>0.260674</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Strike</td>
      <td>0</td>
      <td>4388</td>
      <td>1472</td>
      <td>657</td>
      <td>2.240487</td>
    </tr>
    <tr>
      <th>16</th>
      <td>vitaliy</td>
      <td>3</td>
      <td>30109</td>
      <td>3607</td>
      <td>3247</td>
      <td>1.110872</td>
    </tr>
    <tr>
      <th>21</th>
      <td>JuiceBox</td>
      <td>3</td>
      <td>5639</td>
      <td>1372</td>
      <td>1685</td>
      <td>0.814243</td>
    </tr>
    <tr>
      <th>24</th>
      <td>WAYNE</td>
      <td>3</td>
      <td>12795</td>
      <td>1323</td>
      <td>2296</td>
      <td>0.576220</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Yezpahr</td>
      <td>3</td>
      <td>24143</td>
      <td>3021</td>
      <td>2792</td>
      <td>1.082020</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Peter</td>
      <td>3</td>
      <td>220</td>
      <td>1144</td>
      <td>686</td>
      <td>1.667638</td>
    </tr>
    <tr>
      <th>49</th>
      <td>$$$Ivan@@</td>
      <td>0</td>
      <td>10225</td>
      <td>607</td>
      <td>1003</td>
      <td>0.605184</td>
    </tr>
    <tr>
      <th>53</th>
      <td>Amombob</td>
      <td>0</td>
      <td>2993</td>
      <td>356</td>
      <td>840</td>
      <td>0.423810</td>
    </tr>
    <tr>
      <th>58</th>
      <td>.CaRisMa.</td>
      <td>0</td>
      <td>7617</td>
      <td>1556</td>
      <td>1464</td>
      <td>1.062842</td>
    </tr>
    <tr>
      <th>73</th>
      <td>aimandkill</td>
      <td>3</td>
      <td>10847</td>
      <td>2241</td>
      <td>2463</td>
      <td>0.909866</td>
    </tr>
    <tr>
      <th>75</th>
      <td>Bruce_Bond</td>
      <td>3</td>
      <td>19713</td>
      <td>3464</td>
      <td>2716</td>
      <td>1.275405</td>
    </tr>
    <tr>
      <th>91</th>
      <td>MASSAS</td>
      <td>0</td>
      <td>4489</td>
      <td>108</td>
      <td>375</td>
      <td>0.288000</td>
    </tr>
    <tr>
      <th>92</th>
      <td>coZZixx</td>
      <td>0</td>
      <td>671</td>
      <td>40</td>
      <td>135</td>
      <td>0.296296</td>
    </tr>
    <tr>
      <th>103</th>
      <td>Finduslax</td>
      <td>0</td>
      <td>2963</td>
      <td>636</td>
      <td>1097</td>
      <td>0.579763</td>
    </tr>
    <tr>
      <th>124</th>
      <td>SmokeEST</td>
      <td>0</td>
      <td>2187</td>
      <td>24</td>
      <td>34</td>
      <td>0.705882</td>
    </tr>
    <tr>
      <th>125</th>
      <td>Sikais</td>
      <td>0</td>
      <td>37</td>
      <td>37</td>
      <td>71</td>
      <td>0.521127</td>
    </tr>
    <tr>
      <th>128</th>
      <td>Archesten</td>
      <td>1</td>
      <td>7055</td>
      <td>1178</td>
      <td>604</td>
      <td>1.950331</td>
    </tr>
    <tr>
      <th>135</th>
      <td>Wet_Your_Pants</td>
      <td>2</td>
      <td>12279</td>
      <td>1712</td>
      <td>1708</td>
      <td>1.002342</td>
    </tr>
    <tr>
      <th>146</th>
      <td>Fuet</td>
      <td>2</td>
      <td>15383</td>
      <td>1540</td>
      <td>2573</td>
      <td>0.598523</td>
    </tr>
    <tr>
      <th>155</th>
      <td>Sneekerpikie</td>
      <td>1</td>
      <td>1689</td>
      <td>94</td>
      <td>330</td>
      <td>0.284848</td>
    </tr>
    <tr>
      <th>158</th>
      <td>Forcezx</td>
      <td>2</td>
      <td>6685</td>
      <td>1190</td>
      <td>1572</td>
      <td>0.756997</td>
    </tr>
    <tr>
      <th>160</th>
      <td>NaSko0o</td>
      <td>0</td>
      <td>2156</td>
      <td>33</td>
      <td>156</td>
      <td>0.211538</td>
    </tr>
    <tr>
      <th>163</th>
      <td>Santos</td>
      <td>1</td>
      <td>4024</td>
      <td>299</td>
      <td>338</td>
      <td>0.884615</td>
    </tr>
    <tr>
      <th>168</th>
      <td>Shane</td>
      <td>3</td>
      <td>6079</td>
      <td>1824</td>
      <td>2744</td>
      <td>0.664723</td>
    </tr>
    <tr>
      <th>178</th>
      <td>Peussi_</td>
      <td>3</td>
      <td>12382</td>
      <td>1219</td>
      <td>1069</td>
      <td>1.140318</td>
    </tr>
    <tr>
      <th>190</th>
      <td>Robi_Plavcak</td>
      <td>0</td>
      <td>548</td>
      <td>32</td>
      <td>181</td>
      <td>0.176796</td>
    </tr>
    <tr>
      <th>191</th>
      <td>[EgY]MrKiller</td>
      <td>0</td>
      <td>2184</td>
      <td>170</td>
      <td>271</td>
      <td>0.627306</td>
    </tr>
    <tr>
      <th>205</th>
      <td>ThomaZ[JK]</td>
      <td>0</td>
      <td>6367</td>
      <td>154</td>
      <td>286</td>
      <td>0.538462</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>350775</th>
      <td>[A]dri.</td>
      <td>0</td>
      <td>89</td>
      <td>42</td>
      <td>26</td>
      <td>1.615385</td>
    </tr>
    <tr>
      <th>350827</th>
      <td>Auzen</td>
      <td>0</td>
      <td>17</td>
      <td>14</td>
      <td>11</td>
      <td>1.272727</td>
    </tr>
    <tr>
      <th>350987</th>
      <td>....s....s....s....</td>
      <td>0</td>
      <td>40</td>
      <td>22</td>
      <td>51</td>
      <td>0.431373</td>
    </tr>
    <tr>
      <th>351025</th>
      <td>sSaLeM</td>
      <td>0</td>
      <td>76</td>
      <td>44</td>
      <td>30</td>
      <td>1.466667</td>
    </tr>
    <tr>
      <th>351166</th>
      <td>SS..........SS</td>
      <td>0</td>
      <td>416</td>
      <td>115</td>
      <td>141</td>
      <td>0.815603</td>
    </tr>
    <tr>
      <th>351194</th>
      <td>Rule.</td>
      <td>0</td>
      <td>262</td>
      <td>15</td>
      <td>33</td>
      <td>0.454545</td>
    </tr>
    <tr>
      <th>351346</th>
      <td>SaNTaWy</td>
      <td>0</td>
      <td>129</td>
      <td>51</td>
      <td>36</td>
      <td>1.416667</td>
    </tr>
    <tr>
      <th>351505</th>
      <td>(Xx)cc</td>
      <td>0</td>
      <td>38</td>
      <td>12</td>
      <td>27</td>
      <td>0.444444</td>
    </tr>
    <tr>
      <th>351525</th>
      <td>marte</td>
      <td>0</td>
      <td>344</td>
      <td>16</td>
      <td>89</td>
      <td>0.179775</td>
    </tr>
    <tr>
      <th>351586</th>
      <td>EL_koOK_T0</td>
      <td>0</td>
      <td>442</td>
      <td>37</td>
      <td>87</td>
      <td>0.425287</td>
    </tr>
    <tr>
      <th>351704</th>
      <td>BeNSoON</td>
      <td>0</td>
      <td>44</td>
      <td>25</td>
      <td>12</td>
      <td>2.083333</td>
    </tr>
    <tr>
      <th>351874</th>
      <td>G7]ENd0.</td>
      <td>0</td>
      <td>47</td>
      <td>60</td>
      <td>38</td>
      <td>1.578947</td>
    </tr>
    <tr>
      <th>351895</th>
      <td>[G]enral</td>
      <td>0</td>
      <td>36</td>
      <td>40</td>
      <td>28</td>
      <td>1.428571</td>
    </tr>
    <tr>
      <th>351903</th>
      <td>[S]muFFy.</td>
      <td>0</td>
      <td>193</td>
      <td>58</td>
      <td>50</td>
      <td>1.160000</td>
    </tr>
    <tr>
      <th>351930</th>
      <td>mr____nun30_12</td>
      <td>0</td>
      <td>72</td>
      <td>14</td>
      <td>37</td>
      <td>0.378378</td>
    </tr>
    <tr>
      <th>351951</th>
      <td>Scrimer</td>
      <td>0</td>
      <td>33</td>
      <td>47</td>
      <td>33</td>
      <td>1.424242</td>
    </tr>
    <tr>
      <th>351993</th>
      <td>Tomatsu</td>
      <td>0</td>
      <td>30</td>
      <td>15</td>
      <td>17</td>
      <td>0.882353</td>
    </tr>
    <tr>
      <th>352118</th>
      <td>Sponge</td>
      <td>0</td>
      <td>51</td>
      <td>41</td>
      <td>20</td>
      <td>2.050000</td>
    </tr>
    <tr>
      <th>352160</th>
      <td>oppoooooooooo</td>
      <td>0</td>
      <td>0</td>
      <td>13</td>
      <td>32</td>
      <td>0.406250</td>
    </tr>
    <tr>
      <th>352275</th>
      <td>Anthony_Jones</td>
      <td>0</td>
      <td>211</td>
      <td>113</td>
      <td>55</td>
      <td>2.054545</td>
    </tr>
    <tr>
      <th>352280</th>
      <td>GiiiN[A].</td>
      <td>0</td>
      <td>47</td>
      <td>39</td>
      <td>19</td>
      <td>2.052632</td>
    </tr>
    <tr>
      <th>352635</th>
      <td>[D]rove.</td>
      <td>0</td>
      <td>2</td>
      <td>21</td>
      <td>14</td>
      <td>1.500000</td>
    </tr>
    <tr>
      <th>352706</th>
      <td>[B]One.</td>
      <td>0</td>
      <td>79</td>
      <td>82</td>
      <td>57</td>
      <td>1.438596</td>
    </tr>
    <tr>
      <th>352749</th>
      <td>SWETXX</td>
      <td>0</td>
      <td>12</td>
      <td>26</td>
      <td>13</td>
      <td>2.000000</td>
    </tr>
    <tr>
      <th>353283</th>
      <td>fastxx</td>
      <td>0</td>
      <td>108</td>
      <td>38</td>
      <td>28</td>
      <td>1.357143</td>
    </tr>
    <tr>
      <th>353310</th>
      <td>hi_im_gosu</td>
      <td>0</td>
      <td>70</td>
      <td>13</td>
      <td>44</td>
      <td>0.295455</td>
    </tr>
    <tr>
      <th>353345</th>
      <td>[X]A]S]233</td>
      <td>0</td>
      <td>125</td>
      <td>22</td>
      <td>42</td>
      <td>0.523810</td>
    </tr>
    <tr>
      <th>353485</th>
      <td>SC0RPI0NN</td>
      <td>0</td>
      <td>8</td>
      <td>11</td>
      <td>17</td>
      <td>0.647059</td>
    </tr>
    <tr>
      <th>353592</th>
      <td>[B]oSS.</td>
      <td>0</td>
      <td>71</td>
      <td>30</td>
      <td>13</td>
      <td>2.307692</td>
    </tr>
    <tr>
      <th>353604</th>
      <td>Leongalta</td>
      <td>0</td>
      <td>37</td>
      <td>16</td>
      <td>33</td>
      <td>0.484848</td>
    </tr>
  </tbody>
</table>
<p>3455 rows × 6 columns</p>
</div>

In [16]:
df.nlargest(10, 'kd_ratio')

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Username</th>
      <th>pDonaterRank</th>
      <th>Score</th>
      <th>Kills</th>
      <th>Deaths</th>
      <th>kd_ratio</th>
    </tr>
    <tr>
      <th>Account_ID</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>279</th>
      <td>Police_force</td>
      <td>3</td>
      <td>18932</td>
      <td>2591</td>
      <td>277</td>
      <td>9.353791</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Kar</td>
      <td>3</td>
      <td>1085</td>
      <td>716</td>
      <td>140</td>
      <td>5.114286</td>
    </tr>
    <tr>
      <th>349417</th>
      <td>afiona</td>
      <td>0</td>
      <td>11</td>
      <td>65</td>
      <td>13</td>
      <td>5.000000</td>
    </tr>
    <tr>
      <th>151573</th>
      <td>Barack_Obama</td>
      <td>0</td>
      <td>359</td>
      <td>267</td>
      <td>59</td>
      <td>4.525424</td>
    </tr>
    <tr>
      <th>303527</th>
      <td>.Matrix.</td>
      <td>0</td>
      <td>1</td>
      <td>45</td>
      <td>11</td>
      <td>4.090909</td>
    </tr>
    <tr>
      <th>336064</th>
      <td>CasominX</td>
      <td>0</td>
      <td>8</td>
      <td>51</td>
      <td>14</td>
      <td>3.642857</td>
    </tr>
    <tr>
      <th>228893</th>
      <td>Vex</td>
      <td>0</td>
      <td>375</td>
      <td>204</td>
      <td>60</td>
      <td>3.400000</td>
    </tr>
    <tr>
      <th>286407</th>
      <td>Dragon_007</td>
      <td>0</td>
      <td>83</td>
      <td>147</td>
      <td>46</td>
      <td>3.195652</td>
    </tr>
    <tr>
      <th>176706</th>
      <td>Raekwon_the_Chef</td>
      <td>0</td>
      <td>289</td>
      <td>948</td>
      <td>307</td>
      <td>3.087948</td>
    </tr>
    <tr>
      <th>230054</th>
      <td>Magenta</td>
      <td>0</td>
      <td>618</td>
      <td>335</td>
      <td>109</td>
      <td>3.073394</td>
    </tr>
  </tbody>
</table>
</div>

In [18]:
df.nsmallest(10, 'kd_ratio', 'last')

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Username</th>
      <th>pDonaterRank</th>
      <th>Score</th>
      <th>Kills</th>
      <th>Deaths</th>
      <th>kd_ratio</th>
    </tr>
    <tr>
      <th>Account_ID</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>235494</th>
      <td>zheng</td>
      <td>0</td>
      <td>-876</td>
      <td>18</td>
      <td>785</td>
      <td>0.022930</td>
    </tr>
    <tr>
      <th>145692</th>
      <td>SR7</td>
      <td>0</td>
      <td>-282</td>
      <td>13</td>
      <td>502</td>
      <td>0.025896</td>
    </tr>
    <tr>
      <th>170660</th>
      <td>VitalSpeeD</td>
      <td>0</td>
      <td>27</td>
      <td>11</td>
      <td>378</td>
      <td>0.029101</td>
    </tr>
    <tr>
      <th>89380</th>
      <td>nonnon2012</td>
      <td>0</td>
      <td>-374</td>
      <td>16</td>
      <td>489</td>
      <td>0.032720</td>
    </tr>
    <tr>
      <th>125054</th>
      <td>Alek_Suzic</td>
      <td>0</td>
      <td>328</td>
      <td>11</td>
      <td>296</td>
      <td>0.037162</td>
    </tr>
    <tr>
      <th>201994</th>
      <td>NameLess2230</td>
      <td>0</td>
      <td>502</td>
      <td>12</td>
      <td>307</td>
      <td>0.039088</td>
    </tr>
    <tr>
      <th>463</th>
      <td>noam259</td>
      <td>0</td>
      <td>-471</td>
      <td>16</td>
      <td>397</td>
      <td>0.040302</td>
    </tr>
    <tr>
      <th>251494</th>
      <td>ErolChelebi</td>
      <td>0</td>
      <td>-134</td>
      <td>11</td>
      <td>253</td>
      <td>0.043478</td>
    </tr>
    <tr>
      <th>186590</th>
      <td>goorlik</td>
      <td>0</td>
      <td>-159</td>
      <td>13</td>
      <td>295</td>
      <td>0.044068</td>
    </tr>
    <tr>
      <th>113064</th>
      <td>Cak_Bujas</td>
      <td>0</td>
      <td>218</td>
      <td>12</td>
      <td>270</td>
      <td>0.044444</td>
    </tr>
  </tbody>
</table>
</div>